name: GitHub-Profile-3D-Contrib-and-Summary-Cards

on:
  push:
    branches:
      - master  # Or 'main', depending on your default branch
  schedule:
    - cron: "30 21 * * *"  # Runs at 3:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib-and-summary-cards
    steps:
      - uses: actions/checkout@v3

      # Step to generate the 3D GitHub contribution graph
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Step to generate the GitHub profile summary cards
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all --force 
          git diff-index --quiet HEAD || git commit -m "Generated 3D graph and summary cards"
          git push
