name: GitHub-Profile-3D-Contrib-and-Summary-Cards

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 21 * * *"  # Runs at 3:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib-and-summary-cards
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE }}
          USERNAME: ${{ github.repository_owner }}

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git reset --hard origin/master  # This ensures we are in sync with the latest remote branch
          git add .  # This stages all changes
          git commit -m "generated 3D graph and summary cards" || echo "No changes to commit"
          git push
